export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';

export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const ATTENDANCE_ERROR = 'ATTENDANCE_ERROR';

export const AUTH_TENANT = 'AUTH_TENANT';
export const TENANT_PROCESSING = 'TENANT_PROCESSING';
export const TENANT_LOGOUT = 'TENANT_LOGOUT';
export const TENANT_ERROR = 'TENANT_ERROR';

export const AUTH_USER = 'AUTH_USER';
export const USER_PROCESSING = 'USER_PROCESSING';
export const USER_TASK_FINISHED = 'USER_TASK_FINISHED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_ERROR = 'USER_ERROR';