export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';

export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const ATTENDANCE_ERROR = 'ATTENDANCE_ERROR';

export const AUTH_TENANT = 'AUTH_TENANT';
export const TENANT_ERROR = 'TENANT_ERROR';